export const QUESTIONS = [
  {
    id: "sql-01",
    category: "SQL",
    type: "choice",
    prompt: "student 테이블의 모든 행과 열을 조회하는 문장은?",
    code: null,
    options: ["SELECT ALL FROM student;", "SELECT * FROM student;", "GET * student;", "SHOW student ALL;"],
    answer: 1,
    explanation: "SELECT * FROM 테이블명 형식은 지정한 테이블의 모든 열을 조회한다.",
  },
  {
    id: "sql-02",
    category: "SQL",
    type: "choice",
    prompt: "score가 80 이상인 행만 조회하는 조건으로 올바른 것은?",
    code: "SELECT * FROM student ___ score >= 80;",
    options: ["HAVING", "ORDER BY", "WHERE", "GROUP"],
    answer: 2,
    explanation: "개별 행을 조회 전에 필터링할 때 WHERE를 사용한다.",
  },
  {
    id: "sql-03",
    category: "SQL",
    type: "choice",
    prompt: "name이 '김'으로 시작하는 행을 찾는 조건은?",
    code: null,
    options: ["name LIKE '%김'", "name LIKE '김%'", "name = '김%'", "name LIKE '%김%'"],
    answer: 1,
    explanation: "%는 0개 이상의 문자를 의미하므로 '김%'는 김으로 시작하는 문자열을 찾는다.",
  },
  {
    id: "sql-04",
    category: "SQL",
    type: "choice",
    prompt: "score를 큰 값부터 정렬하는 구문은?",
    code: null,
    options: ["ORDER BY score ASC", "SORT score DOWN", "GROUP BY score DESC", "ORDER BY score DESC"],
    answer: 3,
    explanation: "ORDER BY 열 DESC는 내림차순, ASC는 오름차순 정렬이다.",
  },
  {
    id: "sql-05",
    category: "SQL",
    type: "text",
    prompt: "행의 개수를 세는 집계 함수 이름을 입력하시오.",
    code: "SELECT ___(*) FROM student;",
    answers: ["count", "count()"],
    explanation: "COUNT(*)는 NULL 여부와 관계없이 결과 행의 수를 센다.",
  },
  {
    id: "sql-06",
    category: "SQL",
    type: "choice",
    prompt: "학년별 학생 수를 구할 때 필요한 구문은?",
    code: "SELECT grade, COUNT(*) FROM student ___ grade;",
    options: ["GROUP BY", "ORDER BY", "HAVING", "DISTINCT"],
    answer: 0,
    explanation: "같은 grade 값을 하나의 그룹으로 묶기 위해 GROUP BY를 사용한다.",
  },
  {
    id: "sql-07",
    category: "SQL",
    type: "choice",
    prompt: "그룹화된 결과에서 COUNT(*)가 5 이상인 그룹만 남기는 조건은?",
    code: null,
    options: ["WHERE COUNT(*) >= 5", "HAVING COUNT(*) >= 5", "GROUP COUNT(*) >= 5", "FILTER COUNT(*) >= 5"],
    answer: 1,
    explanation: "집계 결과에 조건을 적용할 때 HAVING을 사용한다.",
  },
  {
    id: "sql-08",
    category: "SQL",
    type: "choice",
    prompt: "중복된 major 값을 제거해 조회하는 구문은?",
    code: null,
    options: ["SELECT UNIQUE major", "SELECT DISTINCT major", "SELECT DIFFERENT major", "SELECT ONLY major"],
    answer: 1,
    explanation: "SELECT DISTINCT는 선택된 열 조합이 같은 중복 행을 제거한다.",
  },
  {
    id: "sql-09",
    category: "SQL",
    type: "choice",
    prompt: "두 SELECT 결과를 중복 제거 없이 모두 합치는 연산자는?",
    code: null,
    options: ["UNION", "UNION ALL", "INTERSECT", "EXCEPT"],
    answer: 1,
    explanation: "UNION ALL은 중복을 유지하고, UNION은 중복을 제거한다.",
  },
  {
    id: "sql-10",
    category: "SQL",
    type: "choice",
    prompt: "두 테이블에서 조인 조건이 일치하는 행만 조회하는 조인은?",
    code: null,
    options: ["LEFT JOIN", "RIGHT JOIN", "INNER JOIN", "FULL OUTER JOIN"],
    answer: 2,
    explanation: "INNER JOIN은 조인 조건이 양쪽에서 일치하는 행만 반환한다.",
  },
  {
    id: "sql-11",
    category: "SQL",
    type: "choice",
    prompt: "왼쪽 테이블의 모든 행을 유지하는 조인은?",
    code: null,
    options: ["LEFT JOIN", "INNER JOIN", "CROSS JOIN", "RIGHT JOIN"],
    answer: 0,
    explanation: "LEFT JOIN은 왼쪽 테이블을 모두 유지하고 오른쪽이 없으면 NULL로 채운다.",
  },
  {
    id: "sql-12",
    category: "SQL",
    type: "choice",
    prompt: "NULL 값을 검사하는 올바른 조건은?",
    code: null,
    options: ["score = NULL", "score == NULL", "score IS NULL", "score EQUAL NULL"],
    answer: 2,
    explanation: "SQL에서 NULL 비교는 =가 아니라 IS NULL 또는 IS NOT NULL을 사용한다.",
  },
  {
    id: "sql-13",
    category: "SQL",
    type: "choice",
    prompt: "새로운 행을 추가하는 명령어는?",
    code: null,
    options: ["APPEND", "INSERT", "UPDATE", "CREATE ROW"],
    answer: 1,
    explanation: "INSERT INTO ... VALUES ... 형식으로 행을 추가한다.",
  },
  {
    id: "sql-14",
    category: "SQL",
    type: "choice",
    prompt: "WHERE 절이 없는 UPDATE 문을 실행했을 때 일반적으로 발생하는 결과는?",
    code: "UPDATE student SET grade = 3;",
    options: ["첫 행만 변경", "마지막 행만 변경", "모든 행 변경", "문법 오류"],
    answer: 2,
    explanation: "WHERE가 없으면 조건으로 제한되지 않아 테이블의 모든 행이 변경된다.",
  },
  {
    id: "sql-15",
    category: "SQL",
    type: "choice",
    prompt: "테이블 구조와 데이터를 함께 삭제하는 DDL 명령은?",
    code: null,
    options: ["DELETE TABLE", "TRUNCATE TABLE", "DROP TABLE", "REMOVE TABLE"],
    answer: 2,
    explanation: "DROP TABLE은 테이블 구조 자체를 제거한다. TRUNCATE는 보통 구조를 유지한다.",
  },
  {
    id: "sql-16",
    category: "SQL",
    type: "choice",
    prompt: "기본키(PRIMARY KEY)의 일반적인 특징은?",
    code: null,
    options: ["중복 허용, NULL 허용", "중복 불가, NULL 불가", "중복 불가, NULL 허용", "중복 허용, NULL 불가"],
    answer: 1,
    explanation: "기본키는 각 행을 식별하므로 중복될 수 없고 NULL도 허용하지 않는다.",
  },
  {
    id: "sql-17",
    category: "SQL",
    type: "choice",
    prompt: "테이블의 열(Column) 개수를 뜻하는 관계형 데이터베이스 용어는?",
    code: null,
    options: ["카디널리티", "차수", "튜플", "도메인"],
    answer: 1,
    explanation: "차수(Degree)는 속성 또는 열의 수이고, 카디널리티는 행 또는 튜플의 수이다.",
  },
  {
    id: "sql-18",
    category: "SQL",
    type: "choice",
    prompt: "테이블 이름 student에 별칭 s를 주는 올바른 표현은?",
    code: null,
    options: ["student TO s", "student AS s", "student NAME s", "student ALIAS = s"],
    answer: 1,
    explanation: "FROM student AS s 또는 FROM student s처럼 별칭을 지정할 수 있다.",
  },
  {
    id: "sql-19",
    category: "SQL",
    type: "choice",
    prompt: "평균 점수를 구하는 집계 함수는?",
    code: null,
    options: ["MEAN(score)", "MID(score)", "AVG(score)", "AVERAGE(score)"],
    answer: 2,
    explanation: "SQL 표준 집계 함수 AVG는 선택된 숫자 값의 평균을 계산한다.",
  },
  {
    id: "sql-20",
    category: "SQL",
    type: "choice",
    prompt: "학생 수가 가장 많은 학년부터 정렬하려면 마지막에 붙일 구문은?",
    code: "SELECT grade, COUNT(*) AS cnt FROM student GROUP BY grade ___;",
    options: ["ORDER BY cnt DESC", "HAVING cnt DESC", "SORT cnt ASC", "GROUP BY cnt DESC"],
    answer: 0,
    explanation: "집계 결과 별칭 cnt를 ORDER BY cnt DESC로 내림차순 정렬할 수 있다.",
  },
  {
    id: "python-01",
    category: "Python",
    type: "choice",
    prompt: "다음 코드의 출력은?",
    code: "numbers = [1, 2, 3]\nprint(numbers[-1])",
    options: ["1", "2", "3", "오류"],
    answer: 2,
    explanation: "Python의 음수 인덱스 -1은 리스트의 마지막 요소를 가리킨다.",
  },
  {
    id: "python-02",
    category: "Python",
    type: "choice",
    prompt: "0부터 4까지 반복하는 표현은?",
    code: null,
    options: ["range(0, 4)", "range(5)", "range(1, 5)", "range(0, 5, 0)"],
    answer: 1,
    explanation: "range(5)는 0, 1, 2, 3, 4를 생성하며 끝값 5는 포함하지 않는다.",
  },
  {
    id: "python-03",
    category: "Python",
    type: "choice",
    prompt: "키-값 쌍을 저장하는 자료형은?",
    code: null,
    options: ["list", "tuple", "dict", "set only"],
    answer: 2,
    explanation: "dict는 해시 가능한 키와 값의 대응 관계를 저장한다.",
  },
  {
    id: "python-04",
    category: "Python",
    type: "choice",
    prompt: "함수를 정의할 때 사용하는 키워드는?",
    code: null,
    options: ["func", "function", "def", "lambda only"],
    answer: 2,
    explanation: "일반 함수 정의는 def 함수명(...): 형식을 사용한다.",
  },
  {
    id: "python-05",
    category: "Python",
    type: "choice",
    prompt: "다음 코드의 출력은?",
    code: "text = 'Python'\nprint(text[1:4])",
    options: ["Pyt", "yth", "ytho", "tho"],
    answer: 1,
    explanation: "슬라이스 [1:4]는 인덱스 1부터 3까지의 'yth'를 반환한다.",
  },
  {
    id: "python-06",
    category: "Python",
    type: "choice",
    prompt: "예외를 직접 처리하기 위한 기본 구문은?",
    code: null,
    options: ["if / else", "try / except", "switch / case", "catch / finally only"],
    answer: 1,
    explanation: "실행 중 발생할 수 있는 예외는 try 블록과 except 블록으로 처리한다.",
  },
  {
    id: "python-07",
    category: "Python",
    type: "text",
    prompt: "리스트의 끝에 값을 추가하는 메서드 이름을 입력하시오.",
    code: "items.___(value)",
    answers: ["append", "append()"],
    explanation: "list.append(value)는 리스트 끝에 value 하나를 추가한다.",
  },
  {
    id: "python-08",
    category: "Python",
    type: "choice",
    prompt: "다음 결과는?",
    code: "values = [x * 2 for x in range(3)]\nprint(values)",
    options: ["[0, 1, 2]", "[0, 2, 4]", "[2, 4, 6]", "[0, 2, 4, 6]"],
    answer: 1,
    explanation: "range(3)의 0, 1, 2에 각각 2를 곱해 [0, 2, 4]가 된다.",
  },
  {
    id: "python-09",
    category: "Python",
    type: "choice",
    prompt: "파일을 with 문으로 여는 주된 장점은?",
    code: null,
    options: ["파일이 자동 암호화됨", "블록 종료 시 파일이 닫힘", "쓰기 속도가 항상 두 배가 됨", "예외가 절대 발생하지 않음"],
    answer: 1,
    explanation: "컨텍스트 관리자(with)는 블록을 벗어날 때 파일 자원을 안전하게 정리한다.",
  },
  {
    id: "python-10",
    category: "Python",
    type: "choice",
    prompt: "객체를 문자열로 표현하도록 정의하는 특수 메서드는?",
    code: null,
    options: ["__init__", "__len__", "__str__", "__main__"],
    answer: 2,
    explanation: "__str__은 str(객체)와 print(객체)에서 사용할 사용자 친화적 문자열을 반환한다.",
  },
  {
    id: "java-01",
    category: "Java",
    type: "choice",
    prompt: "Java 프로그램의 일반적인 진입점 메서드는?",
    code: null,
    options: ["public void start()", "public static void main(String[] args)", "static int run()", "public main()"],
    answer: 1,
    explanation: "JVM은 일반적으로 public static void main(String[] args)를 진입점으로 호출한다.",
  },
  {
    id: "java-02",
    category: "Java",
    type: "choice",
    prompt: "문자열 값 비교에 적절한 메서드는?",
    code: null,
    options: ["== 만 사용", "equals()", "compare pointer", "same()"],
    answer: 1,
    explanation: "String.equals()는 문자열 내용을 비교하고 ==는 참조 동일성을 비교한다.",
  },
  {
    id: "java-03",
    category: "Java",
    type: "choice",
    prompt: "클래스가 다른 클래스를 상속할 때 사용하는 키워드는?",
    code: null,
    options: ["implements", "inherits", "extends", "superclass"],
    answer: 2,
    explanation: "class Child extends Parent 형식으로 클래스 상속을 선언한다.",
  },
  {
    id: "java-04",
    category: "Java",
    type: "choice",
    prompt: "인터페이스를 구현할 때 사용하는 키워드는?",
    code: null,
    options: ["extends only", "implements", "instanceof", "interfaceof"],
    answer: 1,
    explanation: "class Example implements Runnable처럼 implements를 사용한다.",
  },
  {
    id: "java-05",
    category: "Java",
    type: "choice",
    prompt: "다음 코드 실행 결과는?",
    code: "int sum = 0;\nfor (int i = 1; i <= 3; i++) sum += i;\nSystem.out.println(sum);",
    options: ["3", "5", "6", "7"],
    answer: 2,
    explanation: "1 + 2 + 3의 합은 6이다.",
  },
  {
    id: "java-06",
    category: "Java",
    type: "choice",
    prompt: "ArrayList에 요소를 추가하는 메서드는?",
    code: null,
    options: ["append()", "push()", "add()", "insertLast()"],
    answer: 2,
    explanation: "Java의 ArrayList는 add(value)로 요소를 추가한다.",
  },
  {
    id: "java-07",
    category: "Java",
    type: "choice",
    prompt: "예외 처리 구문으로 올바른 조합은?",
    code: null,
    options: ["try / catch", "if / throw only", "check / except", "begin / rescue"],
    answer: 0,
    explanation: "Java는 try 블록에서 발생한 예외를 catch 블록에서 처리한다.",
  },
  {
    id: "java-08",
    category: "Java",
    type: "choice",
    prompt: "객체 생성 시 초기화를 담당하고 클래스명과 같은 이름을 갖는 것은?",
    code: null,
    options: ["소멸자", "생성자", "정적 블록", "인터페이스"],
    answer: 1,
    explanation: "생성자는 반환형을 적지 않고 클래스와 같은 이름을 사용한다.",
  },
  {
    id: "java-09",
    category: "Java",
    type: "choice",
    prompt: "같은 클래스의 모든 인스턴스가 공유하는 멤버를 선언하는 키워드는?",
    code: null,
    options: ["final", "public", "static", "shared"],
    answer: 2,
    explanation: "static 멤버는 특정 객체가 아니라 클래스에 속한다.",
  },
  {
    id: "java-10",
    category: "Java",
    type: "choice",
    prompt: "final 변수에 대한 설명으로 가장 알맞은 것은?",
    code: null,
    options: ["반드시 전역 변수이다", "한 번 초기화한 뒤 다시 대입할 수 없다", "항상 문자열이다", "가비지 컬렉션에서 제외된다"],
    answer: 1,
    explanation: "final 변수는 한 번 값이 정해진 후 다른 값을 다시 대입할 수 없다.",
  },
  {
    id: "linux-01",
    category: "Linux",
    type: "choice",
    prompt: "현재 작업 디렉터리의 절대 경로를 출력하는 명령은?",
    code: null,
    options: ["pwd", "cd", "ls", "where"],
    answer: 0,
    explanation: "pwd는 print working directory의 약자로 현재 경로를 출력한다.",
  },
  {
    id: "linux-02",
    category: "Linux",
    type: "choice",
    prompt: "디렉터리의 파일 목록을 확인하는 명령은?",
    code: null,
    options: ["show", "list", "ls", "dironly"],
    answer: 2,
    explanation: "ls는 현재 또는 지정한 디렉터리의 항목을 나열한다.",
  },
  {
    id: "linux-03",
    category: "Linux",
    type: "choice",
    prompt: "새 디렉터리를 만드는 명령은?",
    code: null,
    options: ["touch", "mkdir", "mkfile", "newdir"],
    answer: 1,
    explanation: "mkdir 디렉터리명 형식으로 새 디렉터리를 만든다.",
  },
  {
    id: "linux-04",
    category: "Linux",
    type: "choice",
    prompt: "파일 권한을 변경하는 명령은?",
    code: null,
    options: ["chown", "chmod", "passwd", "umask only"],
    answer: 1,
    explanation: "chmod는 파일이나 디렉터리의 접근 권한 비트를 변경한다.",
  },
  {
    id: "linux-05",
    category: "Linux",
    type: "choice",
    prompt: "chmod 754에서 소유자의 권한은?",
    code: null,
    options: ["읽기만", "읽기·쓰기", "읽기·실행", "읽기·쓰기·실행"],
    answer: 3,
    explanation: "7은 4(읽기)+2(쓰기)+1(실행)이므로 rwx이다.",
  },
  {
    id: "linux-06",
    category: "Linux",
    type: "choice",
    prompt: "텍스트 파일에서 특정 패턴이 있는 줄을 찾는 명령은?",
    code: null,
    options: ["grep", "findstr only", "cat", "echo"],
    answer: 0,
    explanation: "grep 패턴 파일 형식으로 일치하는 줄을 검색한다.",
  },
  {
    id: "linux-07",
    category: "Linux",
    type: "choice",
    prompt: "실행 중인 프로세스를 확인할 때 주로 사용하는 명령은?",
    code: null,
    options: ["ps", "mv", "cp", "df"],
    answer: 0,
    explanation: "ps는 현재 프로세스 정보를 출력하며 옵션에 따라 범위를 확장할 수 있다.",
  },
  {
    id: "linux-08",
    category: "Linux",
    type: "choice",
    prompt: "표준 출력을 파일 끝에 추가하는 리다이렉션 연산자는?",
    code: null,
    options: [">", ">>", "<", "|"],
    answer: 1,
    explanation: ">>는 파일 끝에 추가하고, >는 일반적으로 파일 내용을 덮어쓴다.",
  },
  {
    id: "linux-09",
    category: "Linux",
    type: "choice",
    prompt: "앞 명령의 출력을 다음 명령의 입력으로 전달하는 연산자는?",
    code: null,
    options: ["&", ";", "|", "#"],
    answer: 2,
    explanation: "파이프(|)는 앞 프로세스의 표준 출력을 뒤 프로세스의 표준 입력으로 연결한다.",
  },
  {
    id: "linux-10",
    category: "Linux",
    type: "text",
    prompt: "사용자 홈 디렉터리를 나타내는 기호를 입력하시오.",
    code: "cd ___",
    answers: ["~"],
    explanation: "셸에서 ~는 현재 사용자의 홈 디렉터리로 확장된다.",
  },
];

